import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  	src: "./fonts/GeistVF.woff",
  	variable: "--font-geist-sans",
  	weight: "100 900",
});
const geistMono = localFont({
 	src: "./fonts/GeistMonoVF.woff",
  	variable: "--font-geist-mono",
  	weight: "100 900",
});

export const metadata: Metadata = {
  	title: "Create Next App",
  	description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <nav>
            <ul>
              <li><a href="/">Home</a></li>
              <li><a href="/about">About</a></li>
              <li><a href="/contact">Contact</a></li>
            </ul>
          </nav>
        </header>
        
        <main>
          {children}
        </main>
        
        <footer>
          <p>© 2023 Your Company</p>
        </footer>
      </body>
    </html>
  );
}
